services:
  snippets-server:
    image: nginx:1.25.3-alpine
    ports:
      - "8001:80"
#      - "8443:443"
    volumes:
      - "./images:/usr/share/nginx/html:rw"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
#      - "./tls.cert.pem:/etc/ssl/cert"
#      - "./tls.key.pem:/etc/ssl/key"
